### ISSUE TITLE
I can't read Text in English? Can you fix it?

### ISSUE THREAD

**Issue by i-cm** [crisxuan/bestJavaer#12]
Yes!
or
No!

1. Moving on to smartphone
2. Open up a menu
3. Translate to English
4. Well done!

> Sorry! You can't translate from PC

**Comment by i-cm** [comment]
Sorry 😞 but you don't fix it.

**Comment by crisxuan** [comment]
Are you my reader ？i'm sorry , l will fix it&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "crisxuan/bestJavaer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月16日(星期五) 上午7:33
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [crisxuan/bestJavaer] I can't read Text in English? Can you fix it? (#12)





 
Sorry 😞 but you don't fix it.

**Comment by i-cm** [comment]
@crisxuan fix this
``` I reopened this issue ```

 1. Moving on to smartphone
 2. Open up a menu
 3. Translate to English
 4. Well done!
