### ISSUE TITLE
sql-improve.md存在笔误

### ISSUE THREAD

**Issue by BlackZhangJian** [crisxuan/bestJavaer#3]
问题位置（加粗）:

1. [ SQL 的书写规范](https://github.com/crisxuan/bestJavaer/blob/master/mysql/sql-improve.md#sql-%E7%9A%84%E4%B9%A6%E5%86%99%E8%A7%84%E8%8C%83)
多行注释很多人不知道，**_这种写法不用可以用来添加真正的溈_**，也可以用来注释代码，非常方便

2. [SQL 性能优化技巧](https://github.com/crisxuan/bestJavaer/blob/master/mysql/sql-improve.md#sql-%E6%80%A7%E8%83%BD%E4%BC%98%E5%8C%96%E6%8A%80%E5%B7%A7)
一、参数是子查询时，使用 EXISTS 代替 IN
。。。。。。
现在我们要查出同时存在于两个表的员工，即**田中和铃木**
田中和铃木表中好像未出现
。。。。。。
三、能写在 WHERE 子句里的条件不要写在 HAVING 子句里
。。。。。。
1.使用 GROUP BY 子句进行聚合时会进行排序，如果事先通过 WHERE 子句能筛选出一部分行，能减轻排序的**钢制**

**Comment by crisxuan** [comment]
已经收到反馈，感谢提出，感谢认可。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"BlackZhangJian"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月14日(星期天) 下午3:00
收件人:&nbsp;"crisxuan/bestJavaer"<bestJavaer@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[crisxuan/bestJavaer] sql-improve.md存在笔误 (#3)





 
问题位置（加粗）:
  
 
 SQL 的书写规范
 多行注释很多人不知道，这种写法不用可以用来添加真正的溈，也可以用来注释代码，非常方便
 
 
 
SQL 性能优化技巧
 一、参数是子查询时，使用 EXISTS 代替 IN
 。。。。。。
 现在我们要查出同时存在于两个表的员工，即田中和铃木
 田中和铃木表中好像未出现
 。。。。。。
 三、能写在 WHERE 子句里的条件不要写在 HAVING 子句里
 。。。。。。
 1.使用 GROUP BY 子句进行聚合时会进行排序，如果事先通过 WHERE 子句能筛选出一部分行，能减轻排序的钢制

**Comment by crisxuan** [comment]
已修改
