### ISSUE TITLE
图片显示不全

### ISSUE THREAD

**Issue by Ray-56** [crisxuan/bestJavaer#5]
具体文件
![](https://raw.githubusercontent.com/Ray-56/image-service/master/picgo/20201026/162126.png)

具体地方
![](https://raw.githubusercontent.com/Ray-56/image-service/master/picgo/20201026162307.png)

**Comment by Ray-56** [comment]
![](https://raw.githubusercontent.com/Ray-56/image-service/master/picgo/20201026/163249.png)
这里也显示不全

**Comment by crisxuan** [comment]
收到，我今天晚上改一下。

**Comment by Ray-56** [comment]
好的好的，感谢作者的分享

**Comment by crisxuan** [comment]
已修改。
