### ISSUE TITLE
小建议

### ISSUE THREAD

**Issue by youthlql** [crisxuan/bestJavaer#6]
Github的md文档没有目录，可不可以提供个在线阅读的版本

**Comment by uptutu** [comment]
可以把 clone 下来然后本地用 Markdown 软件查看，它能根据 H 级别生产一个大纲做目录。

**Comment by crisxuan** [comment]
是的，因为 github 是不允许 md 的[toc] 语法的，所以我还得想一下怎么制作目录。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "crisxuan/bestJavaer"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月13日(星期五) 下午2:28
收件人:&nbsp;"crisxuan/bestJavaer"<bestJavaer@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [crisxuan/bestJavaer] 小建议 (#6)





 
可以把 clone 下来然后本地用 Markdown 软件查看，它能根据 H 级别生产一个大纲做目录。

**Comment by jiaoqiyuan** [comment]
可以考虑一下gitbook

**Comment by crisxuan** [comment]
收到，感谢建议。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "crisxuan/bestJavaer"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月4日(星期五) 中午1:50
收件人:&nbsp;"crisxuan/bestJavaer"<bestJavaer@noreply.github.com&gt;;
抄送:&nbsp;"迟到的旅人"<252279279@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [crisxuan/bestJavaer] 小建议 (#6)





 
可以考虑一下gitbook

**Comment by LubinLew** [comment]
你可以参考一下我的 https://github.com/LubinLew/lubinlew.github.io, 用的是 jekyll, 再自己买个域名就可以了

**Comment by bajins** [comment]
> 你可以参考一下我的 https://github.com/LubinLew/lubinlew.github.io, 用的是 jekyll, 再自己买个域名就可以了

不，我建议使用vuepress或docsify，两者都可以直接在GitHub上部署，示例： https://github.com/woytu/notes-docsify  https://github.com/woytu/notes-vuepress

**Comment by crisxuan** [comment]
已经知道如何给 github 添加md 了，今天处理完成

**Comment by crisxuan** [comment]
所有文章都已经添加目录了，感谢各位支持！
