### ISSUE TITLE
额，这里好像有点录入的问题

### ISSUE THREAD

**Issue by csy-666** [crisxuan/bestJavaer#8]
float 是单精度浮点型，占用 4 位，1 float = 32 bits，默认值是 0.0f；

double 是双精度浮点型，占用 8 位，1 double = 64 bits，默认值是 0.0d；

占4个字节和8个字节吧
java基础里面的

**Comment by csy-666** [comment]
> float 是单精度浮点型，占用 4 位，1 float = 32 bits，默认值是 0.0f；
> 
> double 是双精度浮点型，占用 8 位，1 double = 64 bits，默认值是 0.0d；
> 
> 占4个字节和8个字节吧
  java核心基础里面的

**Comment by crisxuan** [comment]
收到，今天处理完成

**Comment by crisxuan** [comment]
done！！！
